### ISSUE TITLE
Latest commit of master does not work with older GNU radio versions

### ISSUE THREAD

**Issue by ghost** [ghostop14/gr-filerepeater#10]
It would be nice to make the code work across (minimally recent) multiple versions of GNU radio. I have GNU radio 3.7 and had to revert to commit
`130f1f5851a68b4e00fe103727753b9d732c0177	May 29, 2019	Changed state to a pair`
to make it work. Works nicely by the way!

**Comment by ghostop14** [comment]
Hi joaocrespo, unfortunately there are incompatibilities between different versions of GNU Radio that makes that not possible.  What the community has been doing is having maint-<version> branches for legacy versions.  So gr-filerepeater has a maint-3.8 and maint-3.7 branch to work with 3.8 and 3.7 respectively.

**Comment by ghost** [comment]
Ok, sorry for the noobness ghostop14, the maint-3.7 branch works perfectly.
