### ISSUE TITLE
Configurable precision for Vector to Text File sink? 

### ISSUE THREAD

**Issue by devnulling** [ghostop14/gr-filerepeater#4]
Since the floats are converted to text, it'd be useful to have an option to configure the output decimal precision as a block option, to cut down on output file size. 

```
-46.94,-57.24,-45.90,-44.34,-45.73,-46.03,-46.80,-51.20....
```

**Comment by ghostop14** [comment]
Hey devnulling!  Sounds like a good add.  I should have time over the weekend to take a look and add it in.
